### ISSUE TITLE
allow missing policy in `addPolicies` & `removePolicies`

### ISSUE THREAD

**Issue by Shivansh-yadav13** [casbin/casbin-core#9]
In `addPolicies` & `removePolicies`, if there is a missing/existing policy in the list of policies, then the operation is stopped and `false` is return, I think for a huge policy storage and large no. of policy addition/remove operation, if we keep this behavior then I guess it can get hard to know about existing/missing policies in the storage.
I think we should either ignore the missing/existing policy and continue the operation or at least log out about the existing/missing policies that the user is trying to input.

**Comment by Shivansh-yadav13** [comment]
@nodece @hsluoyz @Zxilly what are your thoughts about this?

**Comment by Zxilly** [comment]
This behavior is among the all version of casbin.
 If you want to change it, maybe you should make a RFC at golang version, which is original

**Comment by hsluoyz** [comment]
@tangyang9464 @JalinWang @imp2002 any thoughts?

**Comment by Shivansh-yadav13** [comment]
> This behavior is among the all version of casbin.
If you want to change it, maybe you should make a RFC at golang version, which is original

@hsluoyz @Zxilly 
should I make an issue in golang casbin?

**Comment by tangyang9464** [comment]
> @tangyang9464 @JalinWang @imp2002 any thoughts?

He is right, plz check code and fix later. @JalinWang @imp2002

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 OK. Another thing to notice is that don't break the compatibility.

**Comment by JalinWang** [comment]
> This behavior is among the all version of casbin. If you want to change it, maybe you should make a RFC at golang version, which is original


> > @tangyang9464 @JalinWang @imp2002 any thoughts?
> 
> He is right, plz check code and fix later. @JalinWang @imp2002

It seems that missing/existing policies won't abort the batch operation in the Golang version.
``` golang
func (model Model) RemovePoliciesWithEffected(sec string, ptype string, rules [][]string) [][]string {
	var effected [][]string
	for _, rule := range rules {
		index, ok := model[sec][ptype].PolicyMap[strings.Join(rule, DefaultSep)]

		// HERE it has dealt with the missing policy
		if !ok {
			continue
		}

		effected = append(effected, rule)
		model[sec][ptype].Policy = append(model[sec][ptype].Policy[:index], model[sec][ptype].Policy[index+1:]...)
		delete(model[sec][ptype].PolicyMap, strings.Join(rule, DefaultSep))
		for i := index; i < len(model[sec][ptype].Policy); i++ {
			model[sec][ptype].PolicyMap[strings.Join(model[sec][ptype].Policy[i], DefaultSep)] = i
		}
	}
	return effected
}
```

```golang
// AddPoliciesWithAffected adds policy rules to the model, and returns effected rules.
func (model Model) AddPoliciesWithAffected(sec string, ptype string, rules [][]string) [][]string {
	var effected [][]string
	for _, rule := range rules {
		hashKey := strings.Join(rule, DefaultSep)
		_, ok := model[sec][ptype].PolicyMap[hashKey]

		// HERE it has dealt with the existing policy
		if ok {
			continue
		}
		effected = append(effected, rule)
		model.AddPolicy(sec, ptype, rule)
	}
	return effected
}
```

**Comment by tangyang9464** [comment]
@Shivansh-yadav13 Go-Casbin is already done this.

**Comment by Shivansh-yadav13** [comment]
> @Shivansh-yadav13 Go-Casbin is already done this.

ohk, I will add the same in casbin-core

**Comment by JalinWang** [comment]
> > This behavior is among the all version of casbin. If you want to change it, maybe you should make a RFC at golang version, which is original
> 
> > > @tangyang9464 @JalinWang @imp2002 any thoughts?
> > 
> > 
> > He is right, plz check code and fix later. @JalinWang @imp2002
> 
> It seems that missing/existing policies won't abort the batch operation in the Golang version.
> 
> ```go
> func (model Model) RemovePoliciesWithEffected(sec string, ptype string, rules [][]string) [][]string {
> 	var effected [][]string
> 	for _, rule := range rules {
> 		index, ok := model[sec][ptype].PolicyMap[strings.Join(rule, DefaultSep)]
> 
> 		// HERE it has dealt with the missing policy
> 		if !ok {
> 			continue
> 		}
> 
> 		effected = append(effected, rule)
> 		model[sec][ptype].Policy = append(model[sec][ptype].Policy[:index], model[sec][ptype].Policy[index+1:]...)
> 		delete(model[sec][ptype].PolicyMap, strings.Join(rule, DefaultSep))
> 		for i := index; i < len(model[sec][ptype].Policy); i++ {
> 			model[sec][ptype].PolicyMap[strings.Join(model[sec][ptype].Policy[i], DefaultSep)] = i
> 		}
> 	}
> 	return effected
> }
> ```


Sorry. My bad. The request of adding existing policies will be intercepted before `model.addPolicies()`. 
```go
// addPolicies adds rules to the current policy.
func (e *Enforcer) addPolicies(sec string, ptype string, rules [][]string) (bool, error) {
	if e.dispatcher != nil && e.autoNotifyDispatcher {
		return true, e.dispatcher.AddPolicies(sec, ptype, rules)
	}

	if e.model.HasPolicies(sec, ptype, rules) {
		return false, nil
	}
//...
```
I'll try to propose an issue to deal with the duplication problem in `addPolicies` as well as in update operations https://github.com/casbin/casbin-pg-adapter/issues/42#issuecomment-1207359113. What's more, the adapters' updating behavior should also be considered.
